spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wechatShop?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    # camel case
    driverClassName: com.mysql.cj.jdbc.Driver
    # kebab case,中划线的形式
    #driver-class-name:

    # snake case，下划线形式
    #driver_class_name:

mybatis:
  config-location: classpath:db/mybatis/config.xml